apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontendReplica }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/counter-frontend
          ports:
            - containerPort: 3000
          env:
            - name: API_ORIGIN
              value: http://{{ .Release.Name }}-backend
            - name: FONT_COLOR
              value: '#D40511'
            - name: BACKGROUND_COLOR
              value: '#FFCC00'
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
            limits:
              cpu: 300m
              memory: 300Mi
