apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-redis
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}-backend
      ports:
        - port: 6379
  egress: []
